### ISSUE TITLE
Wrong page size used in informix_smi.json

### ISSUE THREAD

**Issue by jtorreke** [skybet/informix-helpers#4]
In the 1 to last query in the file you're assuming that the pagesize for every chunk is set to 2kB:

```
SELECT SUM((chksize-nfree)*2)/1048576 AS chunk_used_gb, (SUM(chksize)*2)/1048576 AS chunk_total_gb FROM syschunks
```

This should be replaced by `pagesize`:

```
SELECT SUM((chksize-nfree)*pagesize)/1073741824 AS chunk_used_gb, (SUM(chksize*pagesize)/1073741824) AS chunk_total_gb FROM syschunks
```

Thanks for the queries though! :)

**Comment by btdba** [comment]
Hi, what I have posted is correct, at least for systems with a native 2 KB page size such as Linux. If using AIX or Windows you may need to change the 2 to a 4; I haven't been able to test it. It is definitely not correct to replace the '2' with the pagesize in this case. I suggest you cross-check your results with 'onstat -d' as I have just done before posting this.

**Comment by btdba** [comment]
If you can offer some feedback on this response, I can add a version of informix_smi.json to the repository for use on 4 KB page size systems and update the blog post that references this, if that is appropriate.

**Comment by jtorreke** [comment]
I have checked this on my system and deemed it correct.
The page size is not OS dependent by the way. It's supplied when creating the dbspaces. I'm back in the office on Monday and I'll send the `onstat -d` output. Replacing the 2k by pagesize makes the query generic for every OS.

**Comment by btdba** [comment]
Hi,

I am discussing the operating system default page size. On Linux it is 2 KB so you can have dbspaces using page sizes that are a multiple of 2 up up to the maximum of 16.

On Windows and AIX the OS page size is 4 KB so you can only create dbspaces using 4, 8, 12 and 16 KB page sizes.

See https://www.ibm.com/support/knowledgecenter/en/SSGU8G_14.1.0/com.ibm.adref.doc/ids_adr_0029.htm

Don't ask me why this is. It appears to be an Informix thing. I am aware that if you google Linux page size it gives the answer 4 kB.

I again ask which operating system are you using? If you are using Linux I am sure the code is correct for all page sizes (i.e. use a factor of 2 when querying sysmaster:syschunks). This is different to how the data is presented by 'onstat -d'.

To illustrate this, here are chunks with 2, 4, 8 and 16 page sizes respectively as displayed by 'onstat -d':

Chunks
address          chunk/dbs     offset     size       free       bpages     flags pathname
62712268         1      1      0          98304      89152                 PO-B-D /informix_data/file1
63e07028         15     15     2457706    256        3                     PO-B-D /informix_data/file1
63d05028         31     31     2465900    128        0                     PO-B-D /informix_data/file1
63d38028         47     47     2474096    64         11                    PO-B-D /informix_data/file1

As you may know, the offset is always represented in units of the default system page size and this is Linux (2 kB) so the offsets are 0 kB, 4915412 kB, 4931800 kB and 4948192 kB.

The sizes are in the page size of the dbspace so are 196608 kB, 1024 kB, 1024 kB and 1024 kB.

In the SMI interface they look like this:

> select chknum, pagesize, offset, chksize, nfree from syschunks where chknum in (1, 15, 31, 47);

chknum    pagesize               offset     chksize       nfree 
     1        2048                    0       98304       89152
    15        4096              2457706         512           6
    31        8192              2465900         512           0
    47       16384              2474096         512          88

You can see now that both the offsets and the chunk sizes are expressed in the system page size of 2 kB.

I hope this demonstrates why I believe the code to be correct. Indeed we have used it extensively for several years.

My only doubt is whether it works correctly on 4 kB page size systems (Windows and AIX).

Ben.

**Comment by jtorreke** [comment]
Hi btdba,

You're absolutely right and I owe you an apology :-) I'm still a bit confused on the reasons why informix calculates the sizes this way, but your explanation is the only correct outcome.
I'm running my testing installation on an Ubuntu 18.04, indeed reporting 4k pages, but the informix calculations only make sense when using a 2k page size.

Onstat output:

```
user@hostname:~$ onstat -d
                                                                                                                                                                                                                                                                               
IBM Informix Dynamic Server Version 12.10.FC2DE -- On-Line -- Up 3 days 19:52:49 -- 208512 Kbytes                                                                                                                                                                              
                                                                                                                                                                                                                                                                               
Dbspaces
address          number   flags      fchunk   nchunks  pgsize   flags    owner    name
450cd028         1        0x70001    1        1        2048     N  BA    informix rootdbs
451ebc50         2        0x1070001  2        1        2048     N PBA    informix plog
451ebdf8         3        0x60001    3        1        2048     N  BA    informix llog
471f4028         4        0x60001    4        1        2048     N  BA    informix datadbs1
471f41d0         5        0x60001    5        1        2048     N  BA    informix datadbs2
471f4378         6        0x60001    6        1        2048     N  BA    informix datadbs3
471f4520         7        0x60001    7        1        8192     N  BA    informix data8dbs1
471f46c8         8        0x60001    8        1        8192     N  BA    informix data8dbs2
471f4870         9        0x60001    9        1        8192     N  BA    informix data8dbs3
471f4a18         10       0x42001    10       1        8192     N TBA    informix tmpdbspace
471f4bc0         11       0x68001    11       1        2048     N SBA    informix sbspace1
471f4d68         12       0x4a001    12       1        2048     N UBA    informix tmpsbspace
 12 active, 2047 maximum

Chunks
address          chunk/dbs     offset     size       free       bpages     flags pathname
450cd1d0         1      1      0          80896      65024                 PO-B-D /opt/informix/storage/rootdbs
471f6028         2      2      0          32768      0                     PO-BED /opt/informix/storage/ol_informix1210_plog_p_1
471f7028         3      3      0          36352      15                    PO-BED /opt/informix/storage/ol_informix1210_llog_p_1
471f8028         4      4      0          32768      32715                 PO-BED /opt/informix/storage/ol_informix1210_datadbs1_p_1
471f9028         5      5      0          32768      32715                 PO-BED /opt/informix/storage/ol_informix1210_datadbs2_p_1
471fa028         6      6      0          32768      32715                 PO-BED /opt/informix/storage/ol_informix1210_datadbs3_p_1
471fb028         7      7      0          8192       8139                  PO-BED /opt/informix/storage/ol_informix1210_data8dbs1_p_1
471fc028         8      8      0          8192       8139                  PO-BED /opt/informix/storage/ol_informix1210_data8dbs2_p_1
471fd028         9      9      0          8192       8139                  PO-BED /opt/informix/storage/ol_informix1210_data8dbs3_p_1
471fe028         10     10     0          8192       8139                  PO-BE- /opt/informix/storage/ol_informix1210_tmpdbspace_p_1
471ff028         11     11     0          32768      23802      23802      POSB-D /opt/informix/storage/ol_informix1210_sbspace1_p_1
                                 Metadata 1745       8466       1745    
47200028         12     12     0          32768      23802      23802      POSB-- /opt/informix/storage/ol_informix1210_tmpsbspace_p_1
                                 Metadata 1745       8466       1745    
 12 active, 32766 maximum

NOTE: The values in the "size" and "free" columns for DBspace chunks are
      displayed in terms of "pgsize" of the DBspace to which they belong.
```

I salute thee, kind sir :-)

Thanks
Jeroen

**Comment by btdba** [comment]
Hi, no problem.
